<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <link href="http://fonts.googleapis.com/css?family=Alfa+Slab+One|Open+Sans:400,400italic,700,700italic" rel="stylesheet" type="text/css">
	<meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <title>MyMock</title>

  <style>
  
  *, *:before, *:after {
    -moz-box-sizing: border-box;
}
*, *:before, *:after {
    -moz-box-sizing: border-box;
}
html, body {
    font-size: 100%;
	width: 100%;
}
html {
    font-family: sans-serif;
}
*, *:before, *:after {
    -moz-box-sizing: border-box;
}
body {
    background: none repeat scroll 0 0 #003c00;
    color: #222222;
    font-family: "Open Sans","Helvetica",Helvetica,Arial,sans-serif;
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    margin: 0;
    padding: 0;
    position: relative;
	width: 95%;
}
html, body {
    font-size: 100%;
}
.row:after {
    clear: both;
}
.row:before, .row:after {
    content: " ";
    display: table;
}

.row {
    margin: 0 auto;
    max-width: 62.5em;
}
.row .large-12 {
    position: relative;
    width: 100%;
}
.row .column, .row .columns {
    float: left;
    padding-left: 0.9375em;
    padding-right: 0.9375em;
    position: relative;
}
h1, h2, h3, h4, h5, h6 {
    color: #222222;
    font-family: "Open Sans","Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif;
    font-style: normal;
    font-weight: normal;
    line-height: 1.2125em;
    margin-bottom: 0.5em;
    margin-top: 0.2em;
    text-rendering: optimizelegibility;
}
h1 {
    font-size: 2.75em;
	font-family: 'Alfa Slab One', cursive;
	color: #FC0;
}
h2 {
    font-size: 2.3125em;
}
h1, h2, h3, h4, h5, h6 {
    line-height: 1.4;
	color: #FC0;
	font-family: 'Alfa Slab One', cursive;
	font-weight: normal;
}
p, ul {
    font-family: inherit;
    font-size: 1em;
    font-weight: normal;
    line-height: 1.6;
    margin-bottom: 1.25em;
	color: #fff;
}

blockquote {
    border-left: 1px solid #DDDDDD;
    margin: 0 0 1.25em;
    padding: 0.5625em 1.25em 0 1.1875em;
}
blockquote, blockquote p {
    color: #6F6F6F;
    line-height: 1.6;
}
  </style>
  

</head>
<body>

	<div class="row">
		<div class="small-12 columns">
			
			<h1>MyMock</h1>
			
			<h2>How To Play:</h2>
			<p>To get started with MyMock, click on Create MyMock Drafts. Work through your picks in the MyMock Draft Notes tab. Filter the player list by position or by school with the tap of a button.</p>
			<p>Invite friends to get in on the action. Everyone who registers for the app via the Facebook registration, will be entered for a chance to win two tickets to the first round of the 2014 NFL Draft in New York City.</p>
			<p>Need some expert advice? We've crunched the numbers to give you the experts' opinion on team needs to guide your picks. Purchase a Season Pass for access to SIX professional analystsÕ projections by percentage and combine results. All the info you need to create your personal draft war room.</p>
			<h3>Scoring:</h3>
			<p>Your mock draft will be scored using the following point deductions.</p>
			<ul>
				<li>You Start with 100 Points</li>
				<li> (-1 point) For each player that your mock draft has in the first round that is not drafted in the first round</li>
			</ul>
			<p>The following are exclusive deductions, meaning only 1 will apply per pick. The maximum deductions per pick is 4 points.</p>
			<ul>
				<li>(-1 point) For each player that you pick for the correct team but in the wrong draft spot</li>
				<li>(-2 points) For each player that you pick in the correct draft spot but the wrong team </li>
				<li>(-3 points) For each player that you pick the wrong team and wrong draft spot</li>
			</ul>
			<p>In the event of a tie, the winner will be picked based on the amount of time prior to the official start the NFLª Draft that you last saved your mock draft.  Each time you save changes to your mock draft, the timestamp will be updated.</p>
		</div></div>

</body>
</html>
