<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic" rel="stylesheet" type="text/css">
	<meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <title>MyMock</title>

  <style>
  
  *, *:before, *:after {
    -moz-box-sizing: border-box;
}
*, *:before, *:after {
    -moz-box-sizing: border-box;
}
html, body {
    font-size: 100%;
	width: 100%;
}
html {
    font-family: sans-serif;
}
*, *:before, *:after {
    -moz-box-sizing: border-box;
}
body {
    background: none repeat scroll 0 0 white;
    color: #222222;
    font-family: "Open Sans","Helvetica",Helvetica,Arial,sans-serif;
    font-style: normal;
    font-weight: normal;
    line-height: 1;
    margin: 0;
    padding: 0;
    position: relative;
	width: 95%;
}
html, body {
    font-size: 100%;
}
.row:after {
    clear: both;
}
.row:before, .row:after {
    content: " ";
    display: table;
}

.row {
    margin: 0 auto;
    max-width: 62.5em;
}
.row .large-12 {
    position: relative;
    width: 100%;
}
.row .column, .row .columns {
    float: left;
    padding-left: 0.9375em;
    padding-right: 0.9375em;
    position: relative;
}
h1, h2, h3, h4, h5, h6 {
    color: #222222;
    font-family: "Open Sans","Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif;
    font-style: normal;
    font-weight: 700;
    line-height: 1.2125em;
    margin-bottom: 0.5em;
    margin-top: 0.2em;
    text-rendering: optimizelegibility;
}
h1 {
    font-size: 2.75em;
}
h2 {
    font-size: 1.5em;
}
h1, h2, h3, h4, h5, h6 {
    line-height: 1.4;
}
  p {
    font-family: inherit;
    font-size: 1em;
    font-weight: normal;
    line-height: 1.6;
    margin-bottom: 1.25em;
}

blockquote {
    border-left: 1px solid #DDDDDD;
    margin: 0 0 1.25em;
    padding: 0.5625em 1.25em 0 1.1875em;
}
blockquote, blockquote p {
    color: #6F6F6F;
    line-height: 1.6;
}
  </style>
  

</head>
<body>

	<div class="row">
		<div class="small-12 columns">
			
			<h1>MyMock</h1>
			
			<h2>League Results:</h2>
			<p>The league results for each league will be posted here once the draft is complete.</p>
			
		</div>
	</div>

</body>
</html>
