<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }
	body
	{
		width: 100%;
		background-color: #fff;	
	}
	#mainImage
	{
		 width: 250px; 
		 height: 100px;
		 maring-left: 20px;
	}
</style>
<html>
<body>
	<p>User Count: <?php echo $this->userCount; ?></p>
	<p>Mock 1.0 Purchases: <?php echo $this->league1Count; ?></p>
	<p>Mock 2.0 Purchases: <?php echo $this->league2Count; ?></p>
	<p>Inside Info Purchases: <?php echo $this->insideCount; ?></p>
</body>
</html>